# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda3-3.12-24.9"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

conda:
  environment: docs/environment.yaml

python:
  # Install our python package before building the docs so setuptools-scm generates the version for RTD to find.
  install:
    - method: pip
      path: .
