name: konnektor
channels:
  - conda-forge
dependencies:
  - python
  - pip
  #Test
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - coverage
  - mypy
  - nbval
  #Typing
  - typing-extensions
  # Sci
  - numpy
  - scipy
  - networkx
  - scikit-learn
  # Chem
  - rdkit==2024.03.5
  # Vis
  - ipycytoscape
  # docs
  - myst-parser
  - pydata-sphinx-theme

  - pip:
    - dill
    - scikit-mol
    - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@a45f3edd5bc3e973c1a01b577c71efa1b62a65d6
    - git+https://github.com/OpenFreeEnergy/gufe@main
