name: konnektor-docs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - typing-extensions
  - numpy
  - networkx
  - gufe >=1.6.1
  - rdkit==2024.03.5
  - ipycytoscape
  - myst-parser
  - sphinx >=8.0
  - nbsphinx
  - pydata-sphinx-theme
  - tqdm
  - zstandard
  - pip:
    - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@v0.2.0

