name: "CI"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    # Skip CI if changed files only affect the following folders
    # See here for more details: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
    paths-ignore:
      - "docs/*"
  push:
    branches:
      - main
  schedule:
    # Run a cron job once daily
    - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  tests:
    runs-on: ${{ matrix.OS }}-latest
    name: "tests"
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu',]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - os: 'macos'
            python-version: "3.12"

    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          environment-name: konnektor
          cache-environment: true
          cache-downloads: true
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}
          create-args: >-
            python=${{ matrix.python-version }}

      - name: "Install"
        run: pip install --no-deps -e .

      - name: "Test imports"
        run: |
          # if we add more to this, consider changing to for + env vars
          python -Ic "import konnektor"
      - name: "Environment Information"
        run: |
          micromamba info
          micromamba list
      - name: "Run tests"
        run: |
          pytest -n auto -v --cov=konnektor --cov-report=xml
      - name: "Test Notebooks"
        run: |
          # another dep I don't want to include in the env
          pip install --no-deps git+https://github.com/OpenFreeEnergy/kartograf.git
          # Only need to test the notebook(s) in examples/
          pytest -v --nbval-lax examples/

      - name: codecov
        if: ${{ github.repository == 'OpenFreeEnergy/konnektor' && github.event != 'schedule'}}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: True
          verbose: True
